insert into comments (textComments) values ('Заявка с высшим приоритетом');
insert into comments (textComments) values ('Подправить п.2 в заявке');
insert into comments (textComments) values ('Отложенная заявка');
insert into comments (textComments) values ('Недостаточно данных в заявке');
insert into comments (textComments) values ('Заявка не соответствует действительности');
insert into attachs(nameFile, size) values ('item_att_first', 34);
insert into attachs(nameFile, size) values ('item_att_second', 38);
insert into attachs(nameFile, size) values ('item_att_third', 54);
insert into item (textItem, comments_id, attachs_id) values ('first_item', 2, 1);
insert into item (textItem, comments_id, attachs_id) values ('second_item', 4, 2);
insert into item (textItem, comments_id, attachs_id) values ('third_item', 1, 3);
insert into category(name, item_id) values ('На исправление', 1);
insert into category(name, item_id) values ('Не актуальные заявки', 3);
insert into category(name, item_id) values ('В работе', 2);
insert into users(name, secondName, age, item_id) values ('Ilya', 'Shabelnik', 28, 1);
insert into users(name, secondName, age, item_id) values ('Ivan', 'Ivanov', 22, 2);
insert into users(name, secondName, age, item_id) values ('Roma', 'Shishkin', 33, 3);
insert into role(name, users_id) values ('Роль 1', 3);
insert into role(name, users_id) values ('Роль 2', 1);
insert into role(name, users_id) values ('Роль 3', 2);
insert into privelege(namePrivelege) values ('Право 1');
insert into privelege(namePrivelege) values ('Право 2');
insert into privelege(namePrivelege) values ('Право 3');
insert into privelege_role(role_id, privelege_id) values (1, 3);
insert into privelege_role(role_id, privelege_id) values (2, 1);
insert into privelege_role(role_id, privelege_id) values (3, 2);
insert into state(status, item_id) values('Активный', 3);
insert into state(status, item_id) values('Приостановлен', 2);
insert into state(status, item_id) values('В разработке', 1);